# Generated by Django 4.0.4 on 2022-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_filedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='filedatacheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('sha1', models.CharField(max_length=400)),
                ('sha256', models.CharField(max_length=400)),
                ('md5', models.CharField(max_length=400)),
            ],
        ),
    ]
